<?php $this->doctype('HTML5'); ?>
<?php 
  $this->headMeta()->appendHttpEquiv('Content-Type','text/html; charset=UTF-8')
                   ->appendHttpEquiv('Content-Language','en-US');
  $this->headMeta()->appendName('keywords','framework, PHP, productivity')
                   ->appendName('description','framework, PHP, productivity');
?>
<?php $this->headTitle('Faux Mocha') ?>
<?php
  $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Bitter');
  $this->headLink()->appendStylesheet($this->basePath('FmiStudent/css/style.css'));
?>
<?php
$this->headScript()->appendFile($this->basePath('FmiStudent/js/jsAjax.js'));
?>
<?php
  $styles = ".h1{color:red;}";
  $this->headStyle()->appendStyle($styles);
?>
<?php
$this->inlineScript()->appendFile('js/prototype.js');
?>
<?php $this->headScript()->captureStart(); ?>
var BASE_URL = '<?php echo $this->baseUrl ;?>'
<?php $this->headScript()->captureEnd(); ?>